name: SonarCloud
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
            distribution: "temurin"
            java-version: "21"
            cache: "gradle"

      - name: Set gradlew as executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:

          args:
            -Dsonar.projectKey=tiffanyadisuryo_eshop
            -Dsonar.organization=tiffanyadisuryo
            -Dsonar.java.binaries=.
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java