name: SonarCloud
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:

          args:
            -Dsonar.projectKey=tiffanyadisuryo_eshop
            -Dsonar.organization=Tiffany Lindy Adisuryo